@extends('layouts.dashboard')

@section('pending.payment')
    active
@endsection

@section('toolbar')
    @includeIf('parts.toolbar', [
        'links' => [
            'home' => 'home',
            'pending payment' => 'pending.payment',
        ],
    ])
@endsection

@section('content')
    <div class="card">
        <!--begin::Body-->
        <div class="card-body p-lg-17">
            <!--begin::Row-->
            <div class="row g-5 mb-5 mb-lg-15">
                <h1 class="fw-bolder text-dark mb-9">
                    Pending Payment
                    <input type="text" id="searchInput" placeholder="Search Here..." style="margin-left:10px;">
                </h1>
                <div class="table-responsive">
                    <table id="myTable" class="table table-bordered text-center">
                        <thead class="border fw-bold">
                            <tr>
                                <th>SL. No.</th>
                                <td>Generated Date</td>
                                <td>Due Date</td>
                                <td>Paid Date</td>
                                <th>Status</th>
                                <th>Remarks</th>
                                <td>Generated By</td>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody class="border">
                            @forelse ($pending_subscription_fees->sortByDesc('created_at') as $subscription_fee)
                                <tr>
                                    <td>{{ $loop->index + 1 }}</td>
                                    <td>{{ $subscription_fee->generated_date }}</td>
                                    <td>
                                        {{ $subscription_fee->due_date }}
                                        @if ($subscription_fee->status == 'unpaid')
                                            <br>
                                            <span class="badge bg-{{ $subscription_fee->due_date_status['class'] }}">
                                                {{ $subscription_fee->due_date_status['text'] }}
                                            </span>
                                        @endif
                                    </td>
                                    <td>{{ \Carbon\Carbon::parse($subscription_fee->paid_date)->format('d M, Y') }}
                                    </td>
                                    <td>
                                        @if ($subscription_fee->status == 'paid')
                                            <span
                                                class="badge bg-success text-dark">{{ Str::title($subscription_fee->status) }}</span>
                                        @else
                                            <span
                                                class="badge bg-warning text-dark">{{ Str::title($subscription_fee->status) }}</span>
                                        @endif
                                    </td>
                                    <td>{!! $subscription_fee->remarks !!}</td>
                                    <td>{{ $subscription_fee->user->name }}</td>
                                    <td>৳{{ $subscription_fee->package_price }}</td>
                                </tr>
                            @empty
                                <tr class="text-danger">
                                    <td colspan="50">Nothing to show here</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <!--end::Row-->
        </div>
        <!--end::Body-->
    </div>
@endsection

@section('footer_scripts')
    <script>
        document.getElementById('searchInput').addEventListener('keyup', function() {
            let filter = this.value.toLowerCase();
            let rows = document.querySelectorAll('#myTable tbody tr');

            rows.forEach(row => {
                let text = row.textContent.toLowerCase();
                row.style.display = text.includes(filter) ? '' : 'none';
            });
        });
    </script>
@endsection
