@extends('layouts.dashboard')

@section('home')
    active
@endsection

@section('toolbar')
    @includeIf('parts.toolbar', [
        'links' => [
            'home' => 'home',
            'subscription fees' => 'subscription.fees',
        ],
    ])
@endsection

@section('content')
    <div class="card mb-5">
        <!--begin::Body-->
        <div class="card-body">
            <!--begin::Row-->
            <div class="row mb-3">
                <!--begin::Col-->
                <div class="col-md-12 pe-lg-10">
                    <div class="d-flex justify-content-between align-items-center mb-9">
                        <h1 class="fw-bolder text-dark mb-0">
                            Subscription Fees
                        </h1>
                    </div>
                </div>
                <!--end::Col-->
            </div>
            <!--end::Row-->
            <div class="row">
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead class="border fw-bold">
                            <tr>
                                <th>Package Name</th>
                                <th>Package Price</th>
                                <th>Domain Name</th>
                                <th>Created At</th>
                            </tr>
                        </thead>
                        <tbody class="border">
                            <tr>
                                <td>{{ $subscription->package_name }}</td>
                                <td>{{ $subscription->package_price }}</td>
                                <td>{{ $subscription->domain_name ?? "Not Set Yet" }}</td>
                                <td>{{ $subscription->created_at->diffForHumans() }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead class="border fw-bold">
                            <tr>
                                <th>SL. No.</th>
                                <td>Generated Date</td>
                                <td>Due Date</td>
                                <td>Paid Date</td>
                                <th>Status</th>
                                <td>Generated By</td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody class="border">
                            @forelse ($subscription->subscription_fees as $subscription_fee)
                                <tr>
                                    <td>{{ $loop->index + 1 }}</td>
                                    <td>{{ $subscription_fee->generated_date }}</td>
                                    <td>
                                        {{ $subscription_fee->due_date }}
                                        <br>
                                        <span class="badge bg-{{ $subscription_fee->due_date_status['class'] }}">
                                            {{ $subscription_fee->due_date_status['text'] }}
                                        </span>
                                    </td>
                                    <td>{{ $subscription_fee->paid_date ?? 'Not Yet' }}</td>
                                    <td>
                                        <span class="badge bg-secondary text-dark">{{ $subscription_fee->status }}</span>
                                    </td>
                                    <td>{{ $subscription_fee->user->name }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-success" href=""></a>
                                    </td>
                                </tr>
                            @empty
                                <tr class="text-danger">
                                    <td colspan="50">Nothing to show here</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!--end::Body-->
    </div>
@endsection
